title = "Grahvani Gitleaks"

[extend]
useDefault = true

[allowlist]
description = "Allow test files and mock secrets"
paths = [
  '''__tests__''',
  '''_test_''',
  '''_tests_''',
  '''\.test\.''',
  '''\.spec\.''',
]
regexTarget = "match"
regexes = [
  '''gitleaks-ignore''',
  '''test-only''',
  '''mock''',
  '''localhost''',
  '''postgresql://mock''',
]
